spring:
  kafka:
    consumer:
      group-id: "default"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/e-market
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL82Dialect

  topic-create-order:
    name: t.product.create-order
  topic-delete-order:
    name: t.product.delete-order

server:
  port: 8081